function tableSI4 = get_supplementary_information(file_path)%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /net/kryo/work/ursho/PhD/Projects/BlueCloud/Imaging_data/Biovolume_data/table SI-4.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2024/05/23 14:51:17

    %% Import the data
    [~, ~, raw] = xlsread(file_path,'Sheet1');
    raw = raw(2:end,:);
    raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
    stringVectors = string(raw(:,[1,2,3]));
    stringVectors(ismissing(stringVectors)) = '';
    raw = raw(:,[4,5,6]);

    %% Replace non-numeric cells with NaN
    R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
    raw(R) = {NaN}; % Replace non-numeric cells

    %% Create output variable
    data = reshape([raw{:}],size(raw));

    %% Create table
    tableSI4 = table;

    %% Allocate imported array to column variable names
    tableSI4.taxa = stringVectors(:,1);
    tableSI4.livingnonliving = categorical(stringVectors(:,2));
    tableSI4.planktonicfunctionaltype = categorical(stringVectors(:,3));
    tableSI4.trophicgroup = data(:,1);
    tableSI4.ascallingparameterforcarbonconvertion = data(:,2);
    tableSI4.bexponentforcarbonconvertion = data(:,3);

    %% Clear temporary variables
    clearvars data raw stringVectors R;
    
end