function TARAregevents = importfile_TARAregevents(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   TARAREGEVENTS = IMPORTFILE1(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   TARAREGEVENTS = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   TARAregevents = importfile1('TARA_reg_events.csv', 2, 3265);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2025/04/24 19:22:19

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,7,8,10,11,15,16,17]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [3,4,7,8,10,11,15,16,17]);
rawStringColumns = string(raw(:, [1,2,5,6,9,12,13,14,18,19,20,21,22]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [2,3,6,7,8,12,13]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
TARAregevents = table;
TARAregevents.Event = rawStringColumns(:, 1);
TARAregevents.MethodDevice = categorical(rawStringColumns(:, 2));
TARAregevents.Campaign = cell2mat(rawNumericColumns(:, 1));
TARAregevents.Stationlabel = cell2mat(rawNumericColumns(:, 2));
TARAregevents.Commentcommentaboutthestationlabel = categorical(rawStringColumns(:, 3));
TARAregevents.DateTime = rawStringColumns(:, 4);
TARAregevents.Latitude = cell2mat(rawNumericColumns(:, 3));
TARAregevents.Longitude = cell2mat(rawNumericColumns(:, 4));
TARAregevents.DateTime2 = rawStringColumns(:, 5);
TARAregevents.Latitude2 = cell2mat(rawNumericColumns(:, 5));
TARAregevents.Longitude2 = cell2mat(rawNumericColumns(:, 6));
TARAregevents.Localitytargetedbythesamplingevent = categorical(rawStringColumns(:, 6));
TARAregevents.Timeofdayofthesamplingevent = categorical(rawStringColumns(:, 7));
TARAregevents.Envfeaturetargetedbythesamplingeven = categorical(rawStringColumns(:, 8));
TARAregevents.Depthnominalofthesamplingevent = cell2mat(rawNumericColumns(:, 7));
TARAregevents.Depthtopmofthesamplingevent = cell2mat(rawNumericColumns(:, 8));
TARAregevents.Depthbotmofthesamplingevent = cell2mat(rawNumericColumns(:, 9));
TARAregevents.URLfileofeventlogsheetpdfpubl = rawStringColumns(:, 9);
TARAregevents.URLrefofrelatedenvironmentaldata = rawStringColumns(:, 10);
TARAregevents.URLrefofrelatednucleotidesdata = rawStringColumns(:, 11);
TARAregevents.Commentabouttheobjectiveofthesa = categorical(rawStringColumns(:, 12));
TARAregevents.Commentaboutthedeploymentofthes = categorical(rawStringColumns(:, 13));

